### ISSUE TITLE
MDS: ATD-Client: Test with providers: Jump

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1274]

**Comment by sergiogcx** [comment]
Jump works with MDS Client v0.2.0:

![2020-01-25_19-10-36.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/88d5cb5c-ae21-4ca2-823c-1368634b4d3b)

![2020-01-25_19-07-48.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/09ee2309-913a-4a8e-8255-55190aad6906)

**Comment by sergiogcx** [comment]
Version 3 seems to be a hiccup for jump:

```
2020-01-27 15:25:00,554 - DEBUG - MDSClientBase::__request() Attempting request: 1/3 -- Timeout None, Paging: True, Delay: 0
2020-01-27 15:25:00,557 - DEBUG - Starting new HTTPS connection (1): api.uber.com:443
2020-01-27 15:25:00,809 - DEBUG - https://api.uber.com:443 "GET /v0.2/emobility/mds/trips?min_end_time=1578780000&max_end_time=1578783600 HTTP/1.1" 400 127
2020-01-27 15:25:00,812 - DEBUG - MDSClientBase::_build_response() status_code: 400
2020-01-27 15:25:00,812 - DEBUG - MDSClientBase::__request() Reported status: False
2020-01-27 15:25:00,812 - DEBUG - MDSClientBase::__request() Unable to make request: Error: b'{"message":"Invalid request","code":"validation_failed","metadata":{"fields":{"":"Invalid additional property: max_end_time"}}}'
2020-01-27 15:25:00,812 - DEBUG - MDSClientBase::__request() Attempting request: 2/3 -- Timeout None, Paging: True, Delay: 0
2020-01-27 15:25:00,815 - DEBUG - Starting new HTTPS connection (1): api.uber.com:443
2020-01-27 15:25:01,001 - DEBUG - https://api.uber.com:443 "GET /v0.2/emobility/mds/trips?min_end_time=1578780000&max_end_time=1578783600 HTTP/1.1" 400 127
2020-01-27 15:25:01,004 - DEBUG - MDSClientBase::_build_response() status_code: 400
2020-01-27 15:25:01,004 - DEBUG - MDSClientBase::__request() Reported status: False
2020-01-27 15:25:01,004 - DEBUG - MDSClientBase::__request() Unable to make request: Error: b'{"message":"Invalid request","code":"validation_failed","metadata":{"fields":{"":"Invalid additional property: max_end_time"}}}'
2020-01-27 15:25:01,004 - DEBUG - MDSClientBase::__request() Attempting request: 3/3 -- Timeout None, Paging: True, Delay: 0
2020-01-27 15:25:01,007 - DEBUG - Starting new HTTPS connection (1): api.uber.com:443
2020-01-27 15:25:01,187 - DEBUG - https://api.uber.com:443 "GET /v0.2/emobility/mds/trips?min_end_time=1578780000&max_end_time=1578783600 HTTP/1.1" 400 127
2020-01-27 15:25:01,190 - DEBUG - MDSClientBase::_build_response() status_code: 400
2020-01-27 15:25:01,190 - DEBUG - MDSClientBase::__request() Reported status: False
2020-01-27 15:25:01,191 - DEBUG - MDSClientBase::__request() Unable to make request: Error: b'{"message":"Invalid request","code":"validation_failed","metadata":{"fields":{"":"Invalid additional property: max_end_time"}}}'
Traceback (most recent call last):
  File "./run.py", line 95, in <module>
    run()
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./run.py", line 71, in run
    end_time=my_time.get_time_end(utc=True, unix=True)
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/mds/MDSClient.py", line 103, in get_trips
    start_time=start_time, end_time=end_time
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/mds/clients/MDSClient030.py", line 124, in get_trips
    params=None if has_next_link else self.params,
  File "/Users/sergiogc/Development/CityOfAustin/ATD/atd-mds/mds/clients/MDSClientBase.py", line 144, in _request
    % (self.max_attempts, mds_endpoint)
Exception: Max attempts reached (3): could not fetch MDS data at endpoint 'https://api.uber.com/v0.2/emobility/mds/trips'
```

**Comment by sergiogcx** [comment]
Confirmed, Jump is not canonical with version 3. It behaves a lot like Spin in that it says it supports it, but it errors when provided canonical parameters. Closing and moving on.
