### ISSUE TITLE
Investigate / Improve Airflow V2 logging of exceptions

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12780]
A possible downside to the containerization of DAGs means that exceptions thrown inside the docker container that is doing the task may be emitted on STDERR or otherwise are not captured by the XCOM logging system. This can obscure the actual problem at hand and require the operator to simulate the execution of the task inside the production airflow environment. This issue intends to track the discussion and work to remediate this disadvantage, possibly through better exception handling via the docker library inside the DAG or some manipulation of the STDOUT and STDERR data streams to merge these into the STDOUT which is logged "normally" during a successful run.

## background

As seen in the airflow log for a failed DAG execution:

```
9b28c28974d8
*** Found local files:
***   * /opt/airflow/logs/dag_id=vz-cris-import/run_id=manual__2023-07-10T12:23:36.529683+00:00/task_id=invoke_cris_import_via_docker/attempt=1.log
[2023-07-10, 07:23:37 CDT] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vz-cris-import.invoke_cris_import_via_docker manual__2023-07-10T12:23:36.529683+00:00 [queued]>
[2023-07-10, 07:23:37 CDT] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vz-cris-import.invoke_cris_import_via_docker manual__2023-07-10T12:23:36.529683+00:00 [queued]>
[2023-07-10, 07:23:37 CDT] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-10, 07:23:37 CDT] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): invoke_cris_import_via_docker> on 2023-07-10 12:23:36.529683+00:00
[2023-07-10, 07:23:37 CDT] {standard_task_runner.py:57} INFO - Started process 1439 to run task
[2023-07-10, 07:23:37 CDT] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vz-cris-import', 'invoke_cris_import_via_docker', 'manual__2023-07-10T12:23:36.529683+00:00', '--job-id', '5135', '--raw', '--subdir', 'DAGS_FOLDER/vz_cris_import.py', '--cfg-path', '/tmp/tmpe0q6_89a']
[2023-07-10, 07:23:37 CDT] {standard_task_runner.py:85} INFO - Job 5135: Subtask invoke_cris_import_via_docker
[2023-07-10, 07:23:37 CDT] {task_command.py:410} INFO - Running <TaskInstance: vz-cris-import.invoke_cris_import_via_docker manual__2023-07-10T12:23:36.529683+00:00 [running]> on host 9b28c28974d8
[2023-07-10, 07:23:37 CDT] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vz-cris-import' AIRFLOW_CTX_TASK_ID='invoke_cris_import_via_docker' AIRFLOW_CTX_EXECUTION_DATE='2023-07-10T12:23:36.529683+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-10T12:23:36.529683+00:00'
[2023-07-10, 07:23:40 CDT] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/vz_cris_import.py", line 33, in invoke_cris_import_via_docker
    auto_remove=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/docker/models/containers.py", line 888, in run
    container, exit_status, command, image, out
docker.errors.ContainerError: Command 'None' in image 'atddocker/vz-cris-import:latest' returned non-zero exit status 1
[2023-07-10, 07:23:40 CDT] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=vz-cris-import, task_id=invoke_cris_import_via_docker, execution_date=20230710T122336, start_date=20230710T122337, end_date=20230710T122340
[2023-07-10, 07:23:40 CDT] {standard_task_runner.py:109} ERROR - Failed to execute job 5135 for task invoke_cris_import_via_docker (Command 'None' in image 'atddocker/vz-cris-import:latest' returned non-zero exit status 1; 1439)
[2023-07-10, 07:23:40 CDT] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-10, 07:23:40 CDT] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

VS the equivalent execution from inside a worker container:

```
root@9b28c28974d8:/opt/airflow# docker run -it --rm atddocker/vz-cris-import:latest
Traceback (most recent call last):
  File "/app/cris_import.py", line 821, in <module>
    main()
  File "/app/cris_import.py", line 34, in main
    secrets = get_secrets()
  File "/app/cris_import.py", line 197, in get_secrets
    return onepasswordconnectsdk.load_dict(client, REQUIRED_SECRETS)
  File "/usr/local/lib/python3.10/dist-packages/onepasswordconnectsdk/config.py", line 66, in load_dict
    item_vault = _vault_uuid_for_field(field=field, vault_tag=vault_tag)
  File "/usr/local/lib/python3.10/dist-packages/onepasswordconnectsdk/config.py", line 159, in _vault_uuid_for_field
    raise NoVaultSetForFieldException(
onepasswordconnectsdk.config.NoVaultSetForFieldException: There         is no vault for SFTP_endpoint field
root@9b28c28974d8:/opt/airflow#
```

**Comment by johnclary** [comment]
@frankhereford this looks it might be an issue with the Python logging configuration or the container run configuration, because most of our dockerized DAGs to surface error messages.

The looking at one of the service bot DAGs, I do see we're using this [`tty` setting](https://github.com/cityofaustin/atd-airflow/blob/fb048f31ac1370c04521eac3dbd0787d72270e8e/dags/atd_service_bot_intake.py#L73C1-L73C18) which might be the missing piece?

**Comment by johnclary** [comment]
FWIW the service bot script does use a proper [logging configuration](https://github.com/cityofaustin/atd-service-bot/blob/60e4aa8eb6babecab0001b32d0dd4c3c38aa6a75/intake.py#L237), but iirc that should really matter: if your dockerized script uses `print()` statements those should still get logged.
