### ISSUE TITLE
ETL: Fix Email's Extract Download

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1342]
It appears the ETL is failing to download the zip files from CRIS, this is likely due to:

1. A change in the email format
2. A change in the url link

Error message:

```
[2020-01-31 02:05:42,488] {{docker_operator.py:244}} INFO - Url Download: 'https://cris.dot.state.tx.us/secure/Share/app/home/download?token=SECRET_TOKEN'
Download Token: 'SECRET_TOKEN'
Final Download URL: 'https://cris.dot.state.tx.us/secure/extracts/Standard_(2018)/extract_2018_20200124190611153_59113_20200121_HAYSTRAVISWILLIAMSON.zip'
[2020-01-31 02:05:42,489] {{docker_operator.py:244}} INFO - Traceback (most recent call last):
  File "/app/process_cris_request_download.py", line 87, in <module>
    cris_download_link, cris_download_token = extract_email_download_link(cris_email.body)
  File "/app/process/helpers_request_download.py", line 105, in extract_email_download_link
    url = download_link_string.group(1) + download_link_string.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by sergiogcx** [comment]
Fixed, closing now:

![2020-01-31_14-01-58.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8a29b95f-0821-4aed-a47c-6cf64afba76f)
