### ISSUE TITLE
ETL Bug: Requests to CRIS are failing

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2550]
The requests done via Bot to CRIS have been failing for the past few days, this is the output log:

```
Initializing Chrome headless browser.
Logging in to 'https://cris.dot.state.tx.us/'
Filling out agency.
Filling out credentials.
Selecting data extract request
Should wait: 10
Should wait: 10
Selecting Counties to be Included in the Extract
Should wait: 3
Should wait: 10
Selecting type IDS PROCESS
Should wait: 10
Submit Request
[2020-04-30 06:07:17,662] {{docker_operator.py:242}} INFO - Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/splinter/element_list.py", line 42, in __getitem__
    return self._container[index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/process_cris_request.py", line 94, in <module>
    browser.find_by_text("Submit").click()
  File "/usr/local/lib/python3.8/site-packages/splinter/element_list.py", line 76, in __getattr__
    return getattr(self.first, name)
  File "/usr/local/lib/python3.8/site-packages/splinter/element_list.py", line 57, in first
    return self[0]
  File "/usr/local/lib/python3.8/site-packages/splinter/element_list.py", line 44, in __getitem__
    raise ElementDoesNotExist(
splinter.exceptions.ElementDoesNotExist: no elements could be found with text "Submit"
[2020-04-30 06:07:17,916] {{taskinstance.py:1128}} ERROR - docker container failed: {'Error': None, 'StatusCode': 1}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 275, in execute
    return self._run_image()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 246, in _run_image
    raise AirflowException('docker container failed: ' + repr(result))
airflow.exceptions.AirflowException: docker container failed: {'Error': None, 'StatusCode': 1}
[2020-04-30 06:07:17,917] {{taskinstance.py:1170}} INFO - All retries failed; marking task as FAILED.dag_id=atd_visionzero_cris_request_production, task_id=docker_command, execution_date=20200429T060000, start_date=20200430T060623, end_date=20200430T060717
[2020-04-30 06:07:19,173] {{logging_mixin.py:112}} INFO - [2020-04-30 06:07:19,173] {{local_task_job.py:103}} INFO - Task exited with return code 1
```

**Comment by sergiogcx** [comment]
Unsure what the problem may be, I haven't looked into this yet. This could have been caused by a UI change, but I will look into this tomorrow during the meetings:

![2020-05-04_23-34-15](https://user-images.githubusercontent.com/5282430/81035269-dda77d00-8e5f-11ea-8a24-447313281718.png)

**Comment by sergiogcx** [comment]
The CRIS website seems to taking longer than usual in the final page where you submit the request, it seems to take longer than 10 seconds which causes the timer to expire and raise an exception when it cannot find the submit button on page.

**Comment by sergiogcx** [comment]
No longer needed, switched to SFTP. Closing.
