### ISSUE TITLE
VZD | Enable/update/fix non-CR3 (blueform) location associations

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3489]
Errors in Lambda:
```
{'errors': [{'extensions': {'path': '$.selectionSet.find_location_for_noncr3_collision', 'code': 'validation-failed'}, 'message': 'field "find_location_for_noncr3_collision" not found in type: \'query_root\''}]}
(edited)
```
```
[ERROR] KeyError: 'data'
Traceback (most recent call last):
  File "/var/task/app.py", line 137, in handler
    hasura_request(record["body"])
  File "/var/task/app.py", line 83, in hasura_request
    new_location_id = response.json()["data"]["find_location_for_noncr3_collision"][0][
```

**Comment by JaceDeloney** [comment]
Sergio knocked this out earlier this week
